### ISSUE TITLE
More information required

### ISSUE THREAD

**Issue by PadmaB** [cfibmers/open-Autoscaler#2]
Hi,
I referred to your README, it is quite interesting. Do you have more details on the roadmap - the next set of planned features, support for admin UI, support for other dbs [currently it requires couchdb], architecture document, etc?
Kindly let me know if there is any other forum to post these kind of questions, apparently didn't receive any response in the cf-dev mailing list hence posted the question here.
Kind Regards,
Padma

**Comment by boyang9527** [comment]
Here are  several things on roadmap
1.  build the BOSH release so that it can be deployed via BOSH
2.  More tight integration with cloud foundry and Diego, with support of more metrics from native CF
3.  SQL database support ( mysql or postgres )
4.  command lines built as a CF CLI plugin

So far we don't  have UI in the roadmap,  but only expose APIs.

**Comment by boyang9527** [comment]
I will watch the cf-dev mailing list. Besides, we have a slack channel here:
https://cloudfoundry.slack.com/messages/autoscaler/
